let I={};const k="nikke-invite-panel-cache-v1",U=2592e6,$=new Proxy({},{get(t,e){return I.state?.[e]}});function x(t={}){I=t||{}}function o(t){const e=I[t];if(typeof e!="function")throw new Error("invite panel api missing: "+t);return e}function b(...t){return o("getStoredAuthSession")(...t)}function c(...t){return o("escapeHtml")(...t)}function i(...t){return o("localize")(...t)}function C(...t){return o("formatLocalDateTime")(...t)}function p(...t){return o("normalizeInviteCode")(...t)}function h(...t){return o("getPendingInviteCode")(...t)}function S(...t){return o("clearPendingInviteCode")(...t)}function q(...t){return o("userInviteRequest")(...t)}function L(...t){return o("acceptInviteCode")(...t)}function w(...t){return o("showToast")(...t)}function P(...t){return o("getAuthErrorMessage")(...t)}function T(t){return{same_ip:i("\u540C IP","same IP"),same_device:i("\u540C\u8BBE\u5907","same device"),ip_register_limit:i("\u540C IP \u6CE8\u518C\u8FC7\u591A","too many signups from the same IP"),inviter_daily_limit:i("\u4ECA\u65E5\u5956\u52B1\u5DF2\u8FBE\u4E0A\u9650","daily reward limit reached"),inviter_monthly_limit:i("\u672C\u6708\u5956\u52B1\u5DF2\u8FBE\u4E0A\u9650","monthly reward limit reached"),self_invite:i("\u4E0D\u80FD\u9080\u8BF7\u81EA\u5DF1","self invite")}[String(t||"")]||String(t||"")}function N(t,e=""){const n=String(t||"");if(n==="rewarded")return i("\u5DF2\u5956\u52B1","Rewarded");if(n==="manual")return i("\u5DF2\u4EBA\u5DE5\u8865\u53D1","Manual reward");if(n==="blocked"){const r=T(e);return r?`${i("\u672A\u5956\u52B1","Blocked")}: ${r}`:i("\u672A\u5956\u52B1","Blocked")}return i("\u5F85\u5224\u5B9A","Pending")}function R(t=[]){return t.length?t.map(e=>`
    <article class="account-invite-record">
      <div>
        <strong>${c(e.invitedEmailMask||i("\u7528\u6237","User"))}</strong>
        <small>${c(C(e.acceptedAt||e.createdAt))}</small>
      </div>
      <span class="account-invite-status is-${c(e.status||"pending")}">${c(N(e.status,e.blockedReason))}</span>
      ${e.rewardDays?`<b>+${c(e.rewardDays)}${c(i("\u5929","d"))}</b>`:""}
    </article>
  `).join(""):`<div class="account-invite-empty">${c(i("\u6682\u65E0\u9080\u8BF7\u8BB0\u5F55","No invite records yet."))}</div>`}function A(){const t=$.authSession||b(),e=t?.user?.id||t?.user?.email||t?.email||"anonymous";return`${k}:${e}`}function D(){try{const t=localStorage.getItem(A()),e=t?JSON.parse(t):null;if(!e||typeof e!="object"||!e.data)return null;const n=Number(e.cachedAt||0);return!Number.isFinite(n)||Date.now()-n>2592e6?null:e.data}catch{return null}}function B(t){try{localStorage.setItem(A(),JSON.stringify({cachedAt:Date.now(),data:t}))}catch{}}function E(t,e){const n=t.querySelector("[data-invite-status]"),r=t.querySelector("[data-invite-code]"),l=t.querySelector("[data-invite-link]"),d=t.querySelector("[data-invite-records]"),s=p(e?.inviteCode),y=s?M(s):e?.inviteUrl||"";if(r&&(r.textContent=e?.inviteCode||"-"),l&&(l.value=y),d&&(d.innerHTML=R(e?.records||[])),n){const g=e?.seasonAccessPermanent?i("\u6C38\u4E45","Permanent"):e?.seasonAccessExpiresAt?C(e.seasonAccessExpiresAt):i("\u672A\u5F00\u542F","Not active");n.textContent=`${i("\u5DF2\u9080\u8BF7","Invited")} ${e?.invitedCount||0} / ${i("\u5DF2\u5956\u52B1","Rewarded")} ${e?.rewardedCount||0} \xB7 ${i("\u8D5B\u5B63\u6743\u9650\u5230\u671F","Season access expires")}: ${g}`}}function u(t){const e=t.querySelector("[data-pending-invite-confirm]"),n=t.querySelector("[data-pending-invite-code]"),r=h();e&&(e.hidden=!r,n&&(n.textContent=r))}function _(t){const e=h(),n=p(t?.inviteCode);return!e||!n||e!==n?!1:(S(),!0)}function M(t){const e=p(t);if(!e)return"";try{const n=new URL(window.location.href);return n.hash="",n.search="",n.searchParams.set("invite",e),n.toString()}catch{return`?invite=${encodeURIComponent(e)}`}}async function H(t){const e=t?.querySelector("[data-invite-panel]");if(!e)return;const n=e.querySelector("[data-invite-status]"),r=e.querySelector("[data-invite-link]"),l=e.querySelector("[data-invite-copy]"),d=e.querySelector("[data-invite-refresh]"),s=e.querySelector("[data-pending-invite-accept]"),y=e.querySelector("[data-pending-invite-cancel]"),g=()=>{l?.addEventListener("click",async()=>{const a=String(r?.value||"");if(a)try{await navigator.clipboard.writeText(a),w(i("\u9080\u8BF7\u94FE\u63A5\u5DF2\u590D\u5236","Invite link copied."))}catch{r?.select?.(),w(i("\u8BF7\u624B\u52A8\u590D\u5236\u9080\u8BF7\u94FE\u63A5","Please copy the invite link manually."))}})},m=async(a=!1)=>{if(!a){const f=D();if(f)return _(f),E(e,f),u(e),f}n&&(n.textContent=i("\u6B63\u5728\u8BFB\u53D6\u9080\u8BF7\u4FE1\u606F...","Loading invite info..."));const v=await q("GET");return _(v),B(v),E(e,v),u(e),v};g(),d?.addEventListener("click",()=>{m(!0).catch(a=>{n&&(n.textContent=P(a))})}),s?.addEventListener("click",async()=>{const a=h();if(a){s.disabled=!0;try{await L(a),u(e),await m(!0)}finally{s.disabled=!1}}}),y?.addEventListener("click",()=>{S(),u(e)});try{u(e),await m(!1),u(e)}catch(a){n&&(n.textContent=P(a))}}export{H as loadInvitePanel,x as setInvitePanelApi};
