let l={},s=null,c=0;const m="nikke-pwa-install-prompt-v1",w=10080*60*1e3;function d(t={}){l={...l,...t}}function b(t={}){d(t)}function P(t={}){d(t)}function h(){try{return JSON.parse(localStorage.getItem(m)||"{}")||{}}catch{return{}}}function p(t){try{localStorage.setItem(m,JSON.stringify(t||{}))}catch{}}function I(){return!!(window.matchMedia?.("(display-mode: standalone)")?.matches||window.matchMedia?.("(display-mode: fullscreen)")?.matches||window.navigator?.standalone)}function S(){const t=window.navigator?.userAgent||"",e=(window.navigator?.platform||"")==="MacIntel"&&window.navigator?.maxTouchPoints>1;return/iPad|iPhone|iPod/i.test(t)||e}function v(){if(I())return!0;const t=h();if(t.installed)return!0;const a=Number(t.dismissedUntil||0);return Number.isFinite(a)&&a>Date.now()}function o(){document.querySelector(".pwa-install-card")?.remove()}function i(t=w){p({dismissedUntil:Date.now()+t}),o()}function y(){return!!document.querySelector(".help-modal-backdrop, .paid-modal-backdrop, .share-preview-backdrop, .share-mode-backdrop, .ocr-crop-backdrop, .character-detail-backdrop")}function f(t="install",a=1800){clearTimeout(c),c=setTimeout(()=>{c=0,A(t)},a)}function A(t="install"){const{escapeHtml:a,localize:e,showToast:u}=l;if(v())return;if(y()){f(t,5e3);return}o();const r=t==="ios",n=document.createElement("aside");n.className="pwa-install-card",n.setAttribute("role","status"),n.innerHTML=`
    <button class="pwa-install-close" type="button" aria-label="${a(e("\u5173\u95ED\u5B89\u88C5\u63D0\u793A","Close install prompt"))}">x</button>
    <div class="pwa-install-icon" aria-hidden="true">PWA</div>
    <div class="pwa-install-copy">
      <strong>${a(e("\u5B89\u88C5\u5230\u684C\u9762","Install app"))}</strong>
      <span>${a(r?e("\u53EF\u6DFB\u52A0\u5230\u4E3B\u5C4F\u5E55\uFF0C\u50CF App \u4E00\u6837\u6253\u5F00\u3002","Add it to your Home Screen for app-like access."):e("\u50CF App \u4E00\u6837\u6253\u5F00\uFF0C\u66F4\u65B0\u540E\u4E5F\u66F4\u5FEB\u8FDB\u5165\u3002","Open it like an app and return faster after updates."))}</span>
    </div>
    <button class="pwa-install-action" type="button">${a(r?e("\u67E5\u770B\u65B9\u6CD5","How to add"):e("\u5B89\u88C5","Install"))}</button>
  `,n.querySelector(".pwa-install-close")?.addEventListener("click",()=>i()),n.querySelector(".pwa-install-action")?.addEventListener("click",()=>{if(r){i(1440*60*1e3),u(e("\u8BF7\u70B9\u51FB\u6D4F\u89C8\u5668\u5206\u4EAB\u6309\u94AE\uFF0C\u7136\u540E\u9009\u62E9\u201C\u6DFB\u52A0\u5230\u4E3B\u5C4F\u5E55\u201D\u3002","Tap the browser Share button, then choose Add to Home Screen."),{duration:5200});return}g()}),document.body.append(n)}async function g(){const{localize:t,showToast:a}=l,e=s;if(!e){o();return}s=null,o();try{if(await e.prompt(),(await e.userChoice)?.outcome==="accepted"){p({installed:!0}),a(t("\u5DF2\u5F00\u59CB\u5B89\u88C5","Installation started"));return}i()}catch(u){console.warn("PWA install prompt failed",u),i(1440*60*1e3)}}function k(){window.addEventListener("beforeinstallprompt",t=>{t.preventDefault(),s=t,f("install",2200)}),window.addEventListener("appinstalled",()=>{s=null,p({installed:!0}),o()}),S()&&f("ios",4200)}export{o as closePwaInstallPrompt,b as init,k as initPwaInstallPrompt,P as setContext,d as setPwaInstallPromptApi};
