let l={},s=null,c=0;const f="nikke-pwa-install-prompt-v1",w=10080*60*1e3;function d(t={}){l={...l,...t}}function P(t={}){d(t)}function b(t={}){d(t)}function h(){try{return JSON.parse(localStorage.getItem(f)||"{}")||{}}catch{return{}}}function m(t){try{localStorage.setItem(f,JSON.stringify(t||{}))}catch{}}function I(){return!!(window.matchMedia?.("(display-mode: standalone)")?.matches||window.matchMedia?.("(display-mode: fullscreen)")?.matches||window.navigator?.standalone)}function S(){const t=window.navigator?.userAgent||"",a=(window.navigator?.platform||"")==="MacIntel"&&window.navigator?.maxTouchPoints>1;return/iPad|iPhone|iPod/i.test(t)||a}function y(){if(I())return!0;const t=h(),e=Number(t.dismissedUntil||0);return Number.isFinite(e)&&e>Date.now()}function o(){document.querySelector(".pwa-install-card")?.remove()}function i(t=w){m({dismissedUntil:Date.now()+t}),o()}function v(){return!!document.querySelector(".help-modal-backdrop, .paid-modal-backdrop, .share-preview-backdrop, .share-mode-backdrop, .ocr-crop-backdrop, .character-detail-backdrop")}function p(t="install",e=1800){clearTimeout(c),c=setTimeout(()=>{c=0,k(t)},e)}function A(t){t&&(s=t,p("install",2200))}function g(){s=null,m({}),o()}function k(t="install"){const{escapeHtml:e,localize:a,showToast:u}=l;if(y())return;if(v()){p(t,5e3);return}o();const r=t==="ios",n=document.createElement("aside");n.className="pwa-install-card",n.setAttribute("role","status"),n.innerHTML=`
    <button class="pwa-install-close" type="button" aria-label="${e(a("\u5173\u95ED\u5B89\u88C5\u63D0\u793A","Close install prompt"))}">x</button>
    <div class="pwa-install-icon" aria-hidden="true">PWA</div>
    <div class="pwa-install-copy">
      <strong>${e(a("\u5B89\u88C5\u5230\u684C\u9762","Install app"))}</strong>
      <span>${e(r?a("\u53EF\u6DFB\u52A0\u5230\u4E3B\u5C4F\u5E55\uFF0C\u50CF App \u4E00\u6837\u6253\u5F00\u3002","Add it to your Home Screen for app-like access."):a("\u50CF App \u4E00\u6837\u6253\u5F00\uFF0C\u66F4\u65B0\u540E\u4E5F\u66F4\u5FEB\u8FDB\u5165\u3002","Open it like an app and return faster after updates."))}</span>
    </div>
    <button class="pwa-install-action" type="button">${e(r?a("\u67E5\u770B\u65B9\u6CD5","How to add"):a("\u5B89\u88C5","Install"))}</button>
  `,n.querySelector(".pwa-install-close")?.addEventListener("click",()=>i()),n.querySelector(".pwa-install-action")?.addEventListener("click",()=>{if(r){i(1440*60*1e3),u(a("\u8BF7\u70B9\u51FB\u6D4F\u89C8\u5668\u5206\u4EAB\u6309\u94AE\uFF0C\u7136\u540E\u9009\u62E9\u201C\u6DFB\u52A0\u5230\u4E3B\u5C4F\u5E55\u201D\u3002","Tap the browser Share button, then choose Add to Home Screen."),{duration:5200});return}T()}),document.body.append(n)}async function T(){const{localize:t,showToast:e}=l,a=s;if(!a){o();return}s=null,o();try{if(await a.prompt(),(await a.userChoice)?.outcome==="accepted"){e(t("\u5DF2\u5F00\u59CB\u5B89\u88C5","Installation started"));return}i()}catch(u){console.warn("PWA install prompt failed",u),i(1440*60*1e3)}}function E(){S()&&p("ios",4200)}export{o as closePwaInstallPrompt,g as handlePwaInstalled,P as init,E as initPwaInstallPrompt,b as setContext,d as setPwaInstallPromptApi,A as setPwaInstallPromptEvent};
