// Generated by scripts/write-runtime-config.mjs. Do not store secrets here.
window.__NIKKE_CONFIG__ = {
  "env": "production",
  "supabaseUrl": "https://xjdyqxkryqtkiroylygp.supabase.co",
  "functionsBaseUrl": "https://xjdyqxkryqtkiroylygp.supabase.co/functions/v1",
  "publishableKey": "sb_publishable_b5uqRu8YvXZSYoOJu-qScw_VKXtGlYD",
  "generatedAt": "2026-06-30T06:40:24.950Z"
};
