// Generated by scripts/write-runtime-config.mjs. Do not store secrets here.
window.__NIKKE_CONFIG_PROFILES__ = {
  "local": {
    "env": "local",
    "supabaseUrl": "http://127.0.0.1:54321",
    "functionsBaseUrl": "http://127.0.0.1:54321/functions/v1",
    "publishableKey": "sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH"
  },
  "production": {
    "env": "production",
    "supabaseUrl": "https://xjdyqxkryqtkiroylygp.supabase.co",
    "functionsBaseUrl": "https://xjdyqxkryqtkiroylygp.supabase.co/functions/v1",
    "publishableKey": "sb_publishable_b5uqRu8YvXZSYoOJu-qScw_VKXtGlYD"
  }
};
window.__NIKKE_RUNTIME_ENV__ = window.__NIKKE_RUNTIME_ENV__ || "production";
window.__NIKKE_CONFIG__ = window.__NIKKE_CONFIG_PROFILES__[window.__NIKKE_RUNTIME_ENV__] || window.__NIKKE_CONFIG_PROFILES__.local;
